Add the `create_alert_resources` variable
x-qdo/tf_aws_elasticache_redis pull request #4
Opened 2023-08-07 17:51 UTC by AlexxxxxxD

A variable called `create_alert_resources` was added to control the creation of resources. We check the value of the `create_alert_resources` variable. If it is equal to false, then `count` is set to 0, which means that no resource instances will be created.
If the value of `create_alert_resources` is not equal to false, then `count` is set to the value of the `redis_clusters` variable. Therefore, the number of resource instances created will depend on the value of the `redis_clusters` variable.

By default, the variable is set to false.

2023-08-07 18:05 UTC, kuzaxak requested changes

2023-08-07 18:05 UTC, kuzaxak commented on variables.tf
> +variable "create_alert_resources" {
And the topic is required. How will we use the module in that case?

And maybe something like `alerts_enabled` would be more consistent naming. Please check other variables.

2023-08-08 13:10 UTC, kuzaxak requested changes

2023-08-08 13:10 UTC, kuzaxak commented on variables.tf
> +  default     = null
Nope, we should have a proper default here. 96 is a correct one.

2023-08-08 13:11 UTC, kuzaxak commented on variables.tf
> +  description = "A variable to control the creation of resources. If set to false, no resources will be created."
```suggestion
  description = "Create CloudWatch alerts for provisioned clusters. Please set `sns_topic_arn`"
```

Please do not write obvious description, it should add value to the name of variable.

2023-08-08 13:30 UTC, AlexxxxxxD commented on variables.tf
> +  default     = null
Do you suggest leaving `null` only for `sns_topic_arn`, and keeping values for `critical_database_usage_threshold` and `warning_database_usage_threshold`?

2023-08-08 13:31 UTC, kuzaxak commented on variables.tf
> +  default     = null
Yes, why `critical_database_usage_threshold` should be null by default?

2023-08-08 13:34 UTC, kuzaxak commented on variables.tf
> +  default     = null
> In summary, the key point is that variables with default values should be set to values that make sense for the majority of use cases, ensuring that the infrastructure can be provisioned without requiring users to provide every single configuration value. In this specific context, setting a specific default value like 96 for "critical_database_usage_threshold" might be more meaningful than using null.

2023-08-08 13:38 UTC, kuzaxak commented on variables.tf
> +  description = "A variable to control the creation of resources. If set to false, no resources will be created."
or 

`description = "Determines if alert-related resources should be created. When false, associated alerting resources are skipped. Please set `sns_topic_arn`"`

2023-08-08 13:43 UTC, kuzaxak approved these changes

2023-08-08 13:43 UTC, AlexxxxxxD commented on variables.tf
> +  description = "A variable to control the creation of resources. If set to false, no resources will be created."
The last option looks like what we need. Thank you! 
I have made the correction.

2023-08-08 13:51 UTC, merged